### PR TITLE
Additional functionality + code styling fixes

### PR DESCRIPTION
**Pull request by seidnerj**
Added an ImageCropper preprocessor
Added a PillowImage to annotations (original was changed to CVImage and both now inherit from an Abstract class named Image) - this allows easily dealing with animated pictures.
ImageReader is agnostic to the image class type (it needs to be specified when it is initialized though)
Added missing dependencies to requirements.txt, namely pillow and tf2onnx.
TrainLogger console output is now supressed by default
np.float --> float to support newer NumPy releases
Updated .gitignore to exlude pyenv and idea settings

### CODE REVIEW

**Comment by pythonlessons** [comment]
Hi, you did a really nice work. Could you please make a pull request into develop branch? So I will accept it, do some minor review, version update and after releasing a new version in PyPI I'll merge it to main branch

**Comment by seidnerj** [comment]
Thanks! Sure thing, with pleasure but I see you already beat me to it... 🙂

**Comment by pythonlessons** [comment]
Released a new version 1.0.9 that is available to install with pip! :) Thanks for contribution

**Comment by seidnerj** [comment]
My pleasure. I'll create additional pull requests as I add more functionality.

**Comment by pythonlessons** [comment]
> My pleasure. I'll create additional pull requests as I add more functionality.

It would be great to have some unit tests for new functionalities if you create them so it would be easier for me to test and make sure everything is right

**Pull request merged**
